
namespace QL_Sach.Presenstation.UINhanVien
{
    partial class frmNhanVien
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmNhanVien));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btxtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btxtQueQuan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bckbGioiTinh = new System.Windows.Forms.CheckBox();
            this.bdtpNgaySinh = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btxtSoDienThoai = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btxtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btxtTenNhanVien = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btxtIdNhanVien = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel10.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel10.Location = new System.Drawing.Point(71, 343);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(63, 23);
            this.bunifuLabel10.TabIndex = 68;
            this.bunifuLabel10.Text = "Địa Chỉ:";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btxtDiaChi
            // 
            this.btxtDiaChi.AcceptsReturn = false;
            this.btxtDiaChi.AcceptsTab = false;
            this.btxtDiaChi.AnimationSpeed = 200;
            this.btxtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btxtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btxtDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.btxtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btxtDiaChi.BackgroundImage")));
            this.btxtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btxtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btxtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btxtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.btxtDiaChi.BorderRadius = 28;
            this.btxtDiaChi.BorderThickness = 1;
            this.btxtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btxtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtDiaChi.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btxtDiaChi.DefaultText = "";
            this.btxtDiaChi.FillColor = System.Drawing.Color.Black;
            this.btxtDiaChi.ForeColor = System.Drawing.Color.White;
            this.btxtDiaChi.HideSelection = true;
            this.btxtDiaChi.IconLeft = null;
            this.btxtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtDiaChi.IconPadding = 10;
            this.btxtDiaChi.IconRight = null;
            this.btxtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtDiaChi.Lines = new string[0];
            this.btxtDiaChi.Location = new System.Drawing.Point(194, 337);
            this.btxtDiaChi.MaxLength = 32767;
            this.btxtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.btxtDiaChi.Modified = false;
            this.btxtDiaChi.Multiline = false;
            this.btxtDiaChi.Name = "btxtDiaChi";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtDiaChi.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btxtDiaChi.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtDiaChi.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.Black;
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtDiaChi.OnIdleState = stateProperties4;
            this.btxtDiaChi.Padding = new System.Windows.Forms.Padding(3);
            this.btxtDiaChi.PasswordChar = '\0';
            this.btxtDiaChi.PlaceholderForeColor = System.Drawing.Color.White;
            this.btxtDiaChi.PlaceholderText = "Enter text...";
            this.btxtDiaChi.ReadOnly = false;
            this.btxtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btxtDiaChi.SelectedText = "";
            this.btxtDiaChi.SelectionLength = 0;
            this.btxtDiaChi.SelectionStart = 0;
            this.btxtDiaChi.ShortcutsEnabled = true;
            this.btxtDiaChi.Size = new System.Drawing.Size(256, 33);
            this.btxtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btxtDiaChi.TabIndex = 67;
            this.btxtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btxtDiaChi.TextMarginBottom = 0;
            this.btxtDiaChi.TextMarginLeft = 3;
            this.btxtDiaChi.TextMarginTop = 0;
            this.btxtDiaChi.TextPlaceholder = "Enter text...";
            this.btxtDiaChi.UseSystemPasswordChar = false;
            this.btxtDiaChi.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel9.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel9.Location = new System.Drawing.Point(70, 294);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(84, 23);
            this.bunifuLabel9.TabIndex = 66;
            this.bunifuLabel9.Text = "Quê Quán:";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btxtQueQuan
            // 
            this.btxtQueQuan.AcceptsReturn = false;
            this.btxtQueQuan.AcceptsTab = false;
            this.btxtQueQuan.AnimationSpeed = 200;
            this.btxtQueQuan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btxtQueQuan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btxtQueQuan.BackColor = System.Drawing.Color.Transparent;
            this.btxtQueQuan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btxtQueQuan.BackgroundImage")));
            this.btxtQueQuan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btxtQueQuan.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btxtQueQuan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btxtQueQuan.BorderColorIdle = System.Drawing.Color.Silver;
            this.btxtQueQuan.BorderRadius = 28;
            this.btxtQueQuan.BorderThickness = 1;
            this.btxtQueQuan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btxtQueQuan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtQueQuan.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btxtQueQuan.DefaultText = "";
            this.btxtQueQuan.FillColor = System.Drawing.Color.Black;
            this.btxtQueQuan.ForeColor = System.Drawing.Color.White;
            this.btxtQueQuan.HideSelection = true;
            this.btxtQueQuan.IconLeft = null;
            this.btxtQueQuan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtQueQuan.IconPadding = 10;
            this.btxtQueQuan.IconRight = null;
            this.btxtQueQuan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtQueQuan.Lines = new string[0];
            this.btxtQueQuan.Location = new System.Drawing.Point(193, 288);
            this.btxtQueQuan.MaxLength = 32767;
            this.btxtQueQuan.MinimumSize = new System.Drawing.Size(1, 1);
            this.btxtQueQuan.Modified = false;
            this.btxtQueQuan.Multiline = false;
            this.btxtQueQuan.Name = "btxtQueQuan";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtQueQuan.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btxtQueQuan.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtQueQuan.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.Black;
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtQueQuan.OnIdleState = stateProperties8;
            this.btxtQueQuan.Padding = new System.Windows.Forms.Padding(3);
            this.btxtQueQuan.PasswordChar = '\0';
            this.btxtQueQuan.PlaceholderForeColor = System.Drawing.Color.White;
            this.btxtQueQuan.PlaceholderText = "Enter text...";
            this.btxtQueQuan.ReadOnly = false;
            this.btxtQueQuan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btxtQueQuan.SelectedText = "";
            this.btxtQueQuan.SelectionLength = 0;
            this.btxtQueQuan.SelectionStart = 0;
            this.btxtQueQuan.ShortcutsEnabled = true;
            this.btxtQueQuan.Size = new System.Drawing.Size(256, 33);
            this.btxtQueQuan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btxtQueQuan.TabIndex = 65;
            this.btxtQueQuan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btxtQueQuan.TextMarginBottom = 0;
            this.btxtQueQuan.TextMarginLeft = 3;
            this.btxtQueQuan.TextMarginTop = 0;
            this.btxtQueQuan.TextPlaceholder = "Enter text...";
            this.btxtQueQuan.UseSystemPasswordChar = false;
            this.btxtQueQuan.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(70, 444);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(116, 23);
            this.bunifuLabel8.TabIndex = 64;
            this.bunifuLabel8.Text = "Số Điện Thoại:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(70, 396);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(49, 23);
            this.bunifuLabel6.TabIndex = 63;
            this.bunifuLabel6.Text = "Email:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(69, 197);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(78, 23);
            this.bunifuLabel5.TabIndex = 62;
            this.bunifuLabel5.Text = "Giới Tính:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(70, 248);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(87, 23);
            this.bunifuLabel4.TabIndex = 61;
            this.bunifuLabel4.Text = "Ngày Sinh:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(70, 148);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(121, 23);
            this.bunifuLabel3.TabIndex = 60;
            this.bunifuLabel3.Text = "Tên Nhân Viên:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(69, 97);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(110, 23);
            this.bunifuLabel2.TabIndex = 59;
            this.bunifuLabel2.Text = "ID Nhân Viên:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bckbGioiTinh
            // 
            this.bckbGioiTinh.AutoSize = true;
            this.bckbGioiTinh.BackColor = System.Drawing.Color.Transparent;
            this.bckbGioiTinh.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bckbGioiTinh.ForeColor = System.Drawing.Color.White;
            this.bckbGioiTinh.Location = new System.Drawing.Point(193, 196);
            this.bckbGioiTinh.Name = "bckbGioiTinh";
            this.bckbGioiTinh.Size = new System.Drawing.Size(69, 24);
            this.bckbGioiTinh.TabIndex = 58;
            this.bckbGioiTinh.Text = "Nam";
            this.bckbGioiTinh.UseVisualStyleBackColor = false;
            // 
            // bdtpNgaySinh
            // 
            this.bdtpNgaySinh.BackColor = System.Drawing.Color.Transparent;
            this.bdtpNgaySinh.BorderRadius = 13;
            this.bdtpNgaySinh.Color = System.Drawing.Color.White;
            this.bdtpNgaySinh.CustomFormat = "dd/mm/yyyy";
            this.bdtpNgaySinh.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bdtpNgaySinh.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bdtpNgaySinh.DisabledColor = System.Drawing.Color.Gray;
            this.bdtpNgaySinh.DisplayWeekNumbers = false;
            this.bdtpNgaySinh.DPHeight = 0;
            this.bdtpNgaySinh.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bdtpNgaySinh.FillDatePicker = false;
            this.bdtpNgaySinh.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold);
            this.bdtpNgaySinh.ForeColor = System.Drawing.Color.White;
            this.bdtpNgaySinh.Icon = ((System.Drawing.Image)(resources.GetObject("bdtpNgaySinh.Icon")));
            this.bdtpNgaySinh.IconColor = System.Drawing.Color.White;
            this.bdtpNgaySinh.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bdtpNgaySinh.LeftTextMargin = 5;
            this.bdtpNgaySinh.Location = new System.Drawing.Point(193, 242);
            this.bdtpNgaySinh.MinimumSize = new System.Drawing.Size(0, 32);
            this.bdtpNgaySinh.Name = "bdtpNgaySinh";
            this.bdtpNgaySinh.Size = new System.Drawing.Size(256, 32);
            this.bdtpNgaySinh.TabIndex = 57;
            this.bdtpNgaySinh.Value = new System.DateTime(2021, 6, 19, 0, 0, 0, 0);
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.Black;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "Hủy";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges1;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.White;
            this.btnClose.IdleBorderRadius = 28;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.Black;
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(633, 419);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 28;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.BorderRadius = 28;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.BorderRadius = 28;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.BorderRadius = 28;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(74, 38);
            this.btnClose.TabIndex = 56;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Lưu";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges2;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.White;
            this.btnSave.IdleBorderRadius = 28;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(550, 419);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 28;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 28;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.BorderRadius = 28;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 28;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(77, 38);
            this.btnSave.TabIndex = 55;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSize = true;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Thay Đổi Ảnh";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges3;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleBorderRadius = 28;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(577, 370);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 28;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 28;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.BorderRadius = 28;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 28;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(102, 38);
            this.bunifuButton1.TabIndex = 54;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI Semibold", 18.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(69, 24);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(290, 41);
            this.bunifuLabel7.TabIndex = 53;
            this.bunifuLabel7.Text = "Thông Tin Nhân Viên";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btxtSoDienThoai
            // 
            this.btxtSoDienThoai.AcceptsReturn = false;
            this.btxtSoDienThoai.AcceptsTab = false;
            this.btxtSoDienThoai.AnimationSpeed = 200;
            this.btxtSoDienThoai.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btxtSoDienThoai.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btxtSoDienThoai.BackColor = System.Drawing.Color.Transparent;
            this.btxtSoDienThoai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btxtSoDienThoai.BackgroundImage")));
            this.btxtSoDienThoai.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btxtSoDienThoai.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btxtSoDienThoai.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btxtSoDienThoai.BorderColorIdle = System.Drawing.Color.Silver;
            this.btxtSoDienThoai.BorderRadius = 28;
            this.btxtSoDienThoai.BorderThickness = 1;
            this.btxtSoDienThoai.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btxtSoDienThoai.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtSoDienThoai.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btxtSoDienThoai.DefaultText = "";
            this.btxtSoDienThoai.FillColor = System.Drawing.Color.Black;
            this.btxtSoDienThoai.ForeColor = System.Drawing.Color.White;
            this.btxtSoDienThoai.HideSelection = true;
            this.btxtSoDienThoai.IconLeft = null;
            this.btxtSoDienThoai.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtSoDienThoai.IconPadding = 10;
            this.btxtSoDienThoai.IconRight = null;
            this.btxtSoDienThoai.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtSoDienThoai.Lines = new string[0];
            this.btxtSoDienThoai.Location = new System.Drawing.Point(194, 440);
            this.btxtSoDienThoai.MaxLength = 32767;
            this.btxtSoDienThoai.MinimumSize = new System.Drawing.Size(1, 1);
            this.btxtSoDienThoai.Modified = false;
            this.btxtSoDienThoai.Multiline = false;
            this.btxtSoDienThoai.Name = "btxtSoDienThoai";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtSoDienThoai.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btxtSoDienThoai.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtSoDienThoai.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.Black;
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtSoDienThoai.OnIdleState = stateProperties12;
            this.btxtSoDienThoai.Padding = new System.Windows.Forms.Padding(3);
            this.btxtSoDienThoai.PasswordChar = '\0';
            this.btxtSoDienThoai.PlaceholderForeColor = System.Drawing.Color.White;
            this.btxtSoDienThoai.PlaceholderText = "Enter number phone...";
            this.btxtSoDienThoai.ReadOnly = false;
            this.btxtSoDienThoai.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btxtSoDienThoai.SelectedText = "";
            this.btxtSoDienThoai.SelectionLength = 0;
            this.btxtSoDienThoai.SelectionStart = 0;
            this.btxtSoDienThoai.ShortcutsEnabled = true;
            this.btxtSoDienThoai.Size = new System.Drawing.Size(256, 33);
            this.btxtSoDienThoai.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btxtSoDienThoai.TabIndex = 52;
            this.btxtSoDienThoai.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btxtSoDienThoai.TextMarginBottom = 0;
            this.btxtSoDienThoai.TextMarginLeft = 3;
            this.btxtSoDienThoai.TextMarginTop = 0;
            this.btxtSoDienThoai.TextPlaceholder = "Enter number phone...";
            this.btxtSoDienThoai.UseSystemPasswordChar = false;
            this.btxtSoDienThoai.WordWrap = true;
            // 
            // btxtEmail
            // 
            this.btxtEmail.AcceptsReturn = false;
            this.btxtEmail.AcceptsTab = false;
            this.btxtEmail.AnimationSpeed = 200;
            this.btxtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btxtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btxtEmail.BackColor = System.Drawing.Color.Transparent;
            this.btxtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btxtEmail.BackgroundImage")));
            this.btxtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btxtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btxtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btxtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.btxtEmail.BorderRadius = 28;
            this.btxtEmail.BorderThickness = 1;
            this.btxtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btxtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btxtEmail.DefaultText = "";
            this.btxtEmail.FillColor = System.Drawing.Color.Black;
            this.btxtEmail.ForeColor = System.Drawing.Color.White;
            this.btxtEmail.HideSelection = true;
            this.btxtEmail.IconLeft = null;
            this.btxtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtEmail.IconPadding = 10;
            this.btxtEmail.IconRight = null;
            this.btxtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtEmail.Lines = new string[0];
            this.btxtEmail.Location = new System.Drawing.Point(193, 390);
            this.btxtEmail.MaxLength = 32767;
            this.btxtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.btxtEmail.Modified = false;
            this.btxtEmail.Multiline = false;
            this.btxtEmail.Name = "btxtEmail";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtEmail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btxtEmail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtEmail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.Black;
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtEmail.OnIdleState = stateProperties16;
            this.btxtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.btxtEmail.PasswordChar = '\0';
            this.btxtEmail.PlaceholderForeColor = System.Drawing.Color.White;
            this.btxtEmail.PlaceholderText = "Enter email...";
            this.btxtEmail.ReadOnly = false;
            this.btxtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btxtEmail.SelectedText = "";
            this.btxtEmail.SelectionLength = 0;
            this.btxtEmail.SelectionStart = 0;
            this.btxtEmail.ShortcutsEnabled = true;
            this.btxtEmail.Size = new System.Drawing.Size(256, 33);
            this.btxtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btxtEmail.TabIndex = 51;
            this.btxtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btxtEmail.TextMarginBottom = 0;
            this.btxtEmail.TextMarginLeft = 3;
            this.btxtEmail.TextMarginTop = 0;
            this.btxtEmail.TextPlaceholder = "Enter email...";
            this.btxtEmail.UseSystemPasswordChar = false;
            this.btxtEmail.WordWrap = true;
            // 
            // btxtTenNhanVien
            // 
            this.btxtTenNhanVien.AcceptsReturn = false;
            this.btxtTenNhanVien.AcceptsTab = false;
            this.btxtTenNhanVien.AnimationSpeed = 200;
            this.btxtTenNhanVien.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btxtTenNhanVien.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btxtTenNhanVien.BackColor = System.Drawing.Color.Transparent;
            this.btxtTenNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btxtTenNhanVien.BackgroundImage")));
            this.btxtTenNhanVien.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btxtTenNhanVien.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btxtTenNhanVien.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btxtTenNhanVien.BorderColorIdle = System.Drawing.Color.Silver;
            this.btxtTenNhanVien.BorderRadius = 28;
            this.btxtTenNhanVien.BorderThickness = 1;
            this.btxtTenNhanVien.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btxtTenNhanVien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtTenNhanVien.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btxtTenNhanVien.DefaultText = "";
            this.btxtTenNhanVien.FillColor = System.Drawing.Color.Black;
            this.btxtTenNhanVien.ForeColor = System.Drawing.Color.White;
            this.btxtTenNhanVien.HideSelection = true;
            this.btxtTenNhanVien.IconLeft = null;
            this.btxtTenNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtTenNhanVien.IconPadding = 10;
            this.btxtTenNhanVien.IconRight = null;
            this.btxtTenNhanVien.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtTenNhanVien.Lines = new string[0];
            this.btxtTenNhanVien.Location = new System.Drawing.Point(193, 142);
            this.btxtTenNhanVien.MaxLength = 32767;
            this.btxtTenNhanVien.MinimumSize = new System.Drawing.Size(1, 1);
            this.btxtTenNhanVien.Modified = false;
            this.btxtTenNhanVien.Multiline = false;
            this.btxtTenNhanVien.Name = "btxtTenNhanVien";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtTenNhanVien.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btxtTenNhanVien.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtTenNhanVien.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.Black;
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtTenNhanVien.OnIdleState = stateProperties20;
            this.btxtTenNhanVien.Padding = new System.Windows.Forms.Padding(3);
            this.btxtTenNhanVien.PasswordChar = '\0';
            this.btxtTenNhanVien.PlaceholderForeColor = System.Drawing.Color.White;
            this.btxtTenNhanVien.PlaceholderText = "Enter text...";
            this.btxtTenNhanVien.ReadOnly = false;
            this.btxtTenNhanVien.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btxtTenNhanVien.SelectedText = "";
            this.btxtTenNhanVien.SelectionLength = 0;
            this.btxtTenNhanVien.SelectionStart = 0;
            this.btxtTenNhanVien.ShortcutsEnabled = true;
            this.btxtTenNhanVien.Size = new System.Drawing.Size(256, 33);
            this.btxtTenNhanVien.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btxtTenNhanVien.TabIndex = 50;
            this.btxtTenNhanVien.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btxtTenNhanVien.TextMarginBottom = 0;
            this.btxtTenNhanVien.TextMarginLeft = 3;
            this.btxtTenNhanVien.TextMarginTop = 0;
            this.btxtTenNhanVien.TextPlaceholder = "Enter text...";
            this.btxtTenNhanVien.UseSystemPasswordChar = false;
            this.btxtTenNhanVien.WordWrap = true;
            // 
            // btxtIdNhanVien
            // 
            this.btxtIdNhanVien.AcceptsReturn = false;
            this.btxtIdNhanVien.AcceptsTab = false;
            this.btxtIdNhanVien.AnimationSpeed = 200;
            this.btxtIdNhanVien.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.btxtIdNhanVien.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.btxtIdNhanVien.BackColor = System.Drawing.Color.Transparent;
            this.btxtIdNhanVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btxtIdNhanVien.BackgroundImage")));
            this.btxtIdNhanVien.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.btxtIdNhanVien.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btxtIdNhanVien.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btxtIdNhanVien.BorderColorIdle = System.Drawing.Color.Silver;
            this.btxtIdNhanVien.BorderRadius = 28;
            this.btxtIdNhanVien.BorderThickness = 1;
            this.btxtIdNhanVien.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.btxtIdNhanVien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtIdNhanVien.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btxtIdNhanVien.DefaultText = "";
            this.btxtIdNhanVien.FillColor = System.Drawing.Color.Black;
            this.btxtIdNhanVien.ForeColor = System.Drawing.Color.White;
            this.btxtIdNhanVien.HideSelection = true;
            this.btxtIdNhanVien.IconLeft = null;
            this.btxtIdNhanVien.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtIdNhanVien.IconPadding = 10;
            this.btxtIdNhanVien.IconRight = null;
            this.btxtIdNhanVien.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.btxtIdNhanVien.Lines = new string[0];
            this.btxtIdNhanVien.Location = new System.Drawing.Point(194, 95);
            this.btxtIdNhanVien.MaxLength = 32767;
            this.btxtIdNhanVien.MinimumSize = new System.Drawing.Size(1, 1);
            this.btxtIdNhanVien.Modified = false;
            this.btxtIdNhanVien.Multiline = false;
            this.btxtIdNhanVien.Name = "btxtIdNhanVien";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtIdNhanVien.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.btxtIdNhanVien.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtIdNhanVien.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.Black;
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.btxtIdNhanVien.OnIdleState = stateProperties24;
            this.btxtIdNhanVien.Padding = new System.Windows.Forms.Padding(3);
            this.btxtIdNhanVien.PasswordChar = '\0';
            this.btxtIdNhanVien.PlaceholderForeColor = System.Drawing.Color.White;
            this.btxtIdNhanVien.PlaceholderText = "Enter ID...";
            this.btxtIdNhanVien.ReadOnly = false;
            this.btxtIdNhanVien.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.btxtIdNhanVien.SelectedText = "";
            this.btxtIdNhanVien.SelectionLength = 0;
            this.btxtIdNhanVien.SelectionStart = 0;
            this.btxtIdNhanVien.ShortcutsEnabled = true;
            this.btxtIdNhanVien.Size = new System.Drawing.Size(256, 33);
            this.btxtIdNhanVien.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.btxtIdNhanVien.TabIndex = 48;
            this.btxtIdNhanVien.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.btxtIdNhanVien.TextMarginBottom = 0;
            this.btxtIdNhanVien.TextMarginLeft = 3;
            this.btxtIdNhanVien.TextMarginTop = 0;
            this.btxtIdNhanVien.TextPlaceholder = "Enter ID...";
            this.btxtIdNhanVien.UseSystemPasswordChar = false;
            this.btxtIdNhanVien.WordWrap = true;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 139;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(493, 60);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(278, 278);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 69;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox1.Click += new System.EventHandler(this.bunifuPictureBox1_Click);
            // 
            // frmNhanVien
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.ClientSize = new System.Drawing.Size(783, 480);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.btxtDiaChi);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.btxtQueQuan);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bckbGioiTinh);
            this.Controls.Add(this.bdtpNgaySinh);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.btxtSoDienThoai);
            this.Controls.Add(this.btxtEmail);
            this.Controls.Add(this.btxtTenNhanVien);
            this.Controls.Add(this.btxtIdNhanVien);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmNhanVien";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmNhanVien";
            this.Load += new System.EventHandler(this.frmNhanVien_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox btxtDiaChi;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox btxtQueQuan;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.CheckBox bckbGioiTinh;
        private Bunifu.UI.WinForms.BunifuDatePicker bdtpNgaySinh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox btxtSoDienThoai;
        private Bunifu.UI.WinForms.BunifuTextBox btxtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox btxtTenNhanVien;
        private Bunifu.UI.WinForms.BunifuTextBox btxtIdNhanVien;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}