//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sach.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string idHoaDon { get; set; }
        public string TenKhachHang { get; set; }
        public string TenSach { get; set; }
        public string TrangThai { get; set; }
        public string TongTien { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
