//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sach.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string idSach { get; set; }
        public string TenSach { get; set; }
        public string LoaiSach { get; set; }
        public string GiaTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual LoaiSach LoaiSach1 { get; set; }
    }
}
